databases:
  - name: Bordu
    databaseName: bordu
    user: bordu
    plan: free

services:
  - type: web
    name: bordu
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bordu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: 
      - key: WEB_CONCURRENCY
        value: 2 # sensible default